# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uy0qYQxsK_kGUJ58eP95rP_aISIHiUxj
"""

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, Embedding, Conv1D, GlobalMaxPooling1D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from transformers import TFAutoModel
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from google.colab import drive
drive.mount('/content/drive')

# 🔹 Step 1: Load Train Data
train_path = "/content/drive/My Drive/fakenews/train.csv"
if not os.path.exists(train_path):
    raise FileNotFoundError("train.csv not found!")
train_df = pd.read_csv(train_path)

# 🔹 Step 2: Preprocess Data
train_df['title'] = train_df['title'].fillna("")
train_df['text'] = train_df['text'].fillna("")
train_df['combined_text'] = train_df['title'] + " " + train_df['text']

# Tokenization
max_len = 128
vocab_size = 10000
embedding_dim = 128

# Initialize Tokenizer
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(train_df['combined_text'])
X_train_seq = tokenizer.texts_to_sequences(train_df['combined_text'])
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, dtype='int32')

# 🔹 Load Pretrained DeBERTa Model
print("Loading DeBERTa model...")
transformer = TFAutoModel.from_pretrained("microsoft/deberta-v3-small")

def extract_embeddings(model, input_ids, batch_size=8):
    """Extracts embeddings from DeBERTa in mini-batches."""
    all_embeddings = []
    for i in range(0, input_ids.shape[0], batch_size):
        batch_input_ids = tf.convert_to_tensor(input_ids[i:i+batch_size])
        batch_embeddings = model(batch_input_ids).last_hidden_state[:, 0, :]
        all_embeddings.append(batch_embeddings.numpy())
    return np.concatenate(all_embeddings, axis=0)

X_train_bert = extract_embeddings(transformer, X_train_pad, batch_size=8)

# 🔹 Define CNN Model for Feature Extraction
def create_embedding_cnn():
    input_tensor = Input(shape=(max_len,))
    x = Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)(input_tensor)
    x = Conv1D(64, 5, activation='relu')(x)
    x = GlobalMaxPooling1D()(x)
    return Model(input_tensor, x)

embedding_cnn_model = create_embedding_cnn()
X_train_cnn = embedding_cnn_model.predict(X_train_pad)

# Combine DeBERTa and CNN features
X_train_features = np.concatenate([X_train_bert, X_train_cnn], axis=1)

# 🔹 Define Discriminator Model
class Discriminator(Model):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.dense1 = Dense(512, activation='relu')
        self.dense2 = Dense(256, activation='relu')
        self.dense3 = Dense(128, activation='relu')
        self.dense4 = Dense(1, activation='sigmoid')

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.dense2(x)
        x = self.dense3(x)
        return self.dense4(x)

# Initialize and compile the model
discriminator = Discriminator()
discriminator.compile(optimizer=Adam(learning_rate=1e-5), loss='binary_crossentropy', metrics=['accuracy'])

# 🔹 Train the Model
y_train = train_df['label'].values  # Get labels
discriminator.fit(X_train_features, y_train, validation_split=0.2, epochs=500, batch_size=32)

# 🔹 Predict on Train Data
y_train_pred_prob = discriminator.predict(X_train_features)
y_train_pred = (y_train_pred_prob > 0.5).astype(int)

# Compute Performance Metrics
accuracy = accuracy_score(y_train, y_train_pred)
precision = precision_score(y_train, y_train_pred)
recall = recall_score(y_train, y_train_pred)
f1 = f1_score(y_train, y_train_pred)

# Print Metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("\nClassification Report:\n", classification_report(y_train, y_train_pred))

# 🔹 Plot Confusion Matrix
cm = confusion_matrix(y_train, y_train_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Real', 'Fake'], yticklabels=['Real', 'Fake'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Train Data)')
plt.show()

# 🔹 Plot Performance Metrics
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
values = [accuracy, precision, recall, f1]
plt.figure(figsize=(8,5))
plt.bar(metrics, values, color=['blue', 'green', 'orange', 'red'])
plt.ylim([0,1])
plt.ylabel('Score')
plt.title('Performance Metrics (Train Data)')
plt.show()

# 🔹 Save the Trained Model
discriminator.save("/content/drive/My Drive/fakenews/fake_news_discriminator_deberta1.h5")
print("✅ Model Training Complete & Saved!")

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, Embedding, Conv1D, GlobalMaxPooling1D, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from transformers import TFAutoModel
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from google.colab import drive

drive.mount('/content/drive')

# Step 1: Load Train Data
train_path = "/content/drive/My Drive/fakenews/train.csv"
if not os.path.exists(train_path):
    raise FileNotFoundError("train.csv not found!")
train_df = pd.read_csv(train_path)

# Step 2: Preprocess Data
train_df['title'] = train_df['title'].fillna("")
train_df['text'] = train_df['text'].fillna("")
train_df['author'] = train_df['author'].fillna("")  # Include author column

# Combine all textual features
train_df['combined_text'] = train_df['author'] + " " + train_df['title'] + " " + train_df['text']

# Tokenization
max_len = 128
vocab_size = 10000
embedding_dim = 128

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(train_df['combined_text'])
X_train_seq = tokenizer.texts_to_sequences(train_df['combined_text'])
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, dtype='int32')

# Load Pretrained DeBERTa Model
print("Loading DeBERTa model...")
transformer = TFAutoModel.from_pretrained("microsoft/deberta-v3-small")

def extract_embeddings(model, input_ids, batch_size=16):
    all_embeddings = []
    for i in range(0, input_ids.shape[0], batch_size):
        batch_input_ids = tf.convert_to_tensor(input_ids[i:i+batch_size])
        batch_embeddings = model(batch_input_ids).last_hidden_state[:, 0, :]
        all_embeddings.append(batch_embeddings.numpy())
    return np.concatenate(all_embeddings, axis=0)

X_train_bert = extract_embeddings(transformer, X_train_pad, batch_size=16)

# Define CNN Model for Feature Extraction
def create_embedding_cnn():
    input_tensor = Input(shape=(max_len,))
    x = Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)(input_tensor)
    x = Conv1D(128, 5, activation='relu')(x)
    x = GlobalMaxPooling1D()(x)
    return Model(input_tensor, x)

embedding_cnn_model = create_embedding_cnn()
X_train_cnn = embedding_cnn_model.predict(X_train_pad)

# Combine Features
X_train_features = np.concatenate([X_train_bert, X_train_cnn], axis=1)

# Define Discriminator Model
class Discriminator(Model):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.dense1 = Dense(512, activation='relu')
        self.batch_norm1 = BatchNormalization()
        self.dense2 = Dense(256, activation='relu')
        self.batch_norm2 = BatchNormalization()
        self.dropout1 = Dropout(0.3)
        self.dense3 = Dense(128, activation='relu')
        self.batch_norm3 = BatchNormalization()
        self.dense4 = Dense(1, activation='sigmoid')

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.batch_norm1(x)
        x = self.dense2(x)
        x = self.batch_norm2(x)
        x = self.dropout1(x)
        x = self.dense3(x)
        x = self.batch_norm3(x)
        return self.dense4(x)

# Optimized Learning Rate Strategy
initial_learning_rate = 5e-4
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate,
    decay_steps=1000,
    decay_rate=0.96,
    staircase=True
)
optimizer = Adam(learning_rate=lr_schedule)

discriminator = Discriminator()
discriminator.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train Model
y_train = train_df['label'].values
discriminator.fit(X_train_features, y_train, validation_split=0.2, epochs=200, batch_size=128)  # Increased batch size and reduced epochs

# Predictions
y_train_pred_prob = discriminator.predict(X_train_features)
y_train_pred = (y_train_pred_prob > 0.45).astype(int)

# Compute Performance Metrics
accuracy = accuracy_score(y_train, y_train_pred)
precision = precision_score(y_train, y_train_pred)
recall = recall_score(y_train, y_train_pred)
f1 = f1_score(y_train, y_train_pred)

# Print Metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("\nClassification Report:\n", classification_report(y_train, y_train_pred))

# Plot Confusion Matrix
cm = confusion_matrix(y_train, y_train_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Real', 'Fake'], yticklabels=['Real', 'Fake'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Train Data)')
plt.show()

# Save the Trained Model
discriminator.save("/content/drive/My Drive/fakenews/fake_news_discriminator_optimized.h5")
print("✅ Optimized Model Training Complete & Saved!")

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from transformers import TFAutoModel
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from google.colab import drive

# Mount Google Drive (if running on Colab)
drive.mount('/content/drive')

# Step 1: Load Train Data
train_path = "/content/drive/My Drive/fakenews/train.csv"
if not os.path.exists(train_path):
    raise FileNotFoundError("train.csv not found!")
train_df = pd.read_csv(train_path)

# Step 2: Preprocess Data
train_df['title'] = train_df['title'].fillna("")
train_df['text'] = train_df['text'].fillna("")
train_df['author'] = train_df['author'].fillna("")  # Include author column

# Combine all textual features
train_df['combined_text'] = (
    train_df['author'] + " " + train_df['title'] + " " + train_df['text']
)

# Tokenization parameters
max_len = 128
vocab_size = 10000
embedding_dim = 128

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(train_df['combined_text'])
X_train_seq = tokenizer.texts_to_sequences(train_df['combined_text'])
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, dtype='int32')

# Load Pretrained DeBERTa Model
print("Loading DeBERTa model...")
transformer = TFAutoModel.from_pretrained("microsoft/deberta-v3-small")

# Function to extract embeddings from DeBERTa
def extract_embeddings(model, input_ids, batch_size=16):
    all_embeddings = []
    for i in range(0, input_ids.shape[0], batch_size):
        batch_input_ids = tf.convert_to_tensor(input_ids[i:i+batch_size])
        # Use [CLS] token embedding (index 0)
        batch_embeddings = model(batch_input_ids).last_hidden_state[:, 0, :]
        all_embeddings.append(batch_embeddings.numpy())
    return np.concatenate(all_embeddings, axis=0)

# Extract DeBERTa embeddings
X_train_bert = extract_embeddings(transformer, X_train_pad, batch_size=16)

print("Shape of DeBERTa embeddings:", X_train_bert.shape)
# For example, (num_samples, 768) if 'microsoft/deberta-v3-small' is used.

# Step 3: Define Discriminator Model
class Discriminator(Model):
    def __init__(self, input_dim):
        super(Discriminator, self).__init__()
        # Explicitly define input shape for the first Dense layer
        self.dense1 = Dense(512, activation='relu', input_shape=(input_dim,))
        self.batch_norm1 = BatchNormalization()
        self.dense2 = Dense(256, activation='relu')
        self.batch_norm2 = BatchNormalization()
        self.dropout1 = Dropout(0.3)
        self.dense3 = Dense(128, activation='relu')
        self.batch_norm3 = BatchNormalization()
        self.dense4 = Dense(1, activation='sigmoid')

    def call(self, inputs, training=False):
        x = self.dense1(inputs)
        x = self.batch_norm1(x, training=training)
        x = self.dense2(x)
        x = self.batch_norm2(x, training=training)
        x = self.dropout1(x, training=training)
        x = self.dense3(x)
        x = self.batch_norm3(x, training=training)
        return self.dense4(x)

# Initialize Discriminator
discriminator = Discriminator(input_dim=X_train_bert.shape[1])

# Build the model to avoid potential shape issues
discriminator.build(input_shape=(None, X_train_bert.shape[1]))

# Learning Rate Decay
initial_learning_rate = 5e-4
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate,
    decay_steps=1000,
    decay_rate=0.96,
    staircase=True
)
optimizer = Adam(learning_rate=lr_schedule)

discriminator.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Step 4: Train the Model
y_train = train_df['label'].values

# Lower batch_size to avoid memory issues (e.g., 64) or keep 128 if GPU has enough memory
discriminator.fit(
    X_train_bert,
    y_train,
    validation_split=0.2,
    epochs=200,
    batch_size=64  # Adjust if needed
)

# Step 5: Predictions
y_train_pred_prob = discriminator.predict(X_train_bert)
# Use threshold of 0.45 to classify as Fake
y_train_pred = (y_train_pred_prob > 0.45).astype(int)

# Step 6: Performance Metrics
accuracy = accuracy_score(y_train, y_train_pred)
precision = precision_score(y_train, y_train_pred)
recall = recall_score(y_train, y_train_pred)
f1 = f1_score(y_train, y_train_pred)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("\nClassification Report:\n", classification_report(y_train, y_train_pred))

# Step 7: Plot Confusion Matrix
cm = confusion_matrix(y_train, y_train_pred)
plt.figure(figsize=(6,5))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=['Real', 'Fake'], yticklabels=['Real', 'Fake']
)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Train Data)')
plt.show()

# Step 8: Save the Trained Model
discriminator.save("/content/drive/My Drive/fakenews/fake_news_discriminator_optimized.h5")
print("✅ Optimized Model Training Complete & Saved!")

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Dense, Dropout, BatchNormalization, Layer, Lambda
)
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report
)
from google.colab import drive

# 1. MOUNT GOOGLE DRIVE & READ DATA
drive.mount('/content/drive')

train_path = "/content/drive/My Drive/fakenews/train.csv"
if not os.path.exists(train_path):
    raise FileNotFoundError("train.csv not found!")
train_df = pd.read_csv(train_path)

train_df['title'] = train_df['title'].fillna("")
train_df['text'] = train_df['text'].fillna("")
train_df['author'] = train_df['author'].fillna("")
train_df['combined_text'] = train_df['author'] + " " + train_df['title'] + " " + train_df['text']
y_train = train_df['label'].values

# 2. INSTALL & IMPORT HUGGING FACE TRANSFORMERS
!pip install -q transformers
from transformers import TFAutoModel, AutoTokenizer

model_name = "microsoft/deberta-v3-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# 3. TOKENIZATION (RETURNS TF TENSORS)
encoded_inputs = tokenizer(
    list(train_df['combined_text']),
    return_tensors="tf",   # Return TensorFlow Tensors
    padding=True,
    truncation=True,
    max_length=128
)
X_input_ids = encoded_inputs["input_ids"]            # shape: (num_samples, 128)
X_attention_masks = encoded_inputs["attention_mask"] # shape: (num_samples, 128)

# 4. CREATE A CUSTOM WRAPPER LAYER FOR DEBERTA
class DebertaLayer(Layer):
    def __init__(self, model_name, **kwargs):
        super().__init__(**kwargs)
        self.transformer = TFAutoModel.from_pretrained(model_name)
        # Unfreeze all layers for fine-tuning
        for layer in self.transformer.layers:
            layer.trainable = True

    def call(self, inputs, training=False):
        input_ids, attention_mask = inputs
        outputs = self.transformer(
            input_ids=input_ids,
            attention_mask=attention_mask,
            training=training
        )
        # outputs.last_hidden_state => (batch_size, seq_len, hidden_dim)
        return outputs.last_hidden_state

# 5. BUILD THE MODEL WITH KERAS FUNCTIONAL API
#    a) Keras Input layers
input_ids_layer = Input(shape=(128,), dtype=tf.int32, name="input_ids")
attention_mask_layer = Input(shape=(128,), dtype=tf.int32, name="attention_mask")

#    b) Pass inputs through custom DeBERTa wrapper
deberta_layer = DebertaLayer(model_name=model_name)
hidden_states = deberta_layer([input_ids_layer, attention_mask_layer])
# shape: (batch_size, seq_len, hidden_dim)

#    c) Mean Pooling via Lambda Layer
mean_pool_layer = Lambda(lambda x: tf.reduce_mean(x, axis=1), name="mean_pool")
mean_pooled = mean_pool_layer(hidden_states)  # shape: (batch_size, hidden_dim)

#    d) Classification Head
x = Dense(512, activation='relu')(mean_pooled)
x = BatchNormalization()(x)
x = Dropout(0.3)(x)

x = Dense(256, activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.3)(x)

x = Dense(128, activation='relu')(x)
x = BatchNormalization()(x)

output = Dense(1, activation='sigmoid')(x)

model = Model(inputs=[input_ids_layer, attention_mask_layer], outputs=output)

# 6. COMPILE & TRAIN
optimizer = Adam(learning_rate=1e-5)  # typical LR for Transformer fine-tuning
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)


model.fit(
    x=[X_input_ids, X_attention_masks],
    y=y_train,
    validation_split=0.2,
    epochs=15,
    batch_size=32
)

# 7. PREDICTIONS & EVALUATION
y_pred_prob = model.predict([X_input_ids, X_attention_masks])
y_pred = (y_pred_prob > 0.45).astype(int)

acc = accuracy_score(y_train, y_pred)
prec = precision_score(y_train, y_pred)
rec = recall_score(y_train, y_pred)
f1 = f1_score(y_train, y_pred)

print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1-Score:  {f1:.4f}\n")
print("Classification Report:\n", classification_report(y_train, y_pred))

cm = confusion_matrix(y_train, y_pred)
plt.figure(figsize=(6,5))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=['Real', 'Fake'],
    yticklabels=['Real', 'Fake']
)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Train Data)')
plt.show()

# 8. SAVE MODEL
model.save("/content/drive/My Drive/fakenews/fake_news_discriminator_finetuned.h5")
print("✅ Fine-tuned Model Training Complete & Saved!")

import matplotlib.pyplot as plt

# Training Data Metrics
train_acc = 0.9668
train_prec = 0.9494
train_rec = 0.9863
train_f1 = 0.9675

print(f"Accuracy:  {train_acc:.4f}")
print(f"Precision: {train_prec:.4f}")
print(f"Recall:    {train_rec:.4f}")
print(f"F1-Score:  {train_f1:.4f}\n")

# Plot Training Performance Metrics
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
train_values = [train_acc, train_prec, train_rec, train_f1]

plt.figure(figsize=(8,5))
plt.bar(metrics, train_values, color=['blue', 'green', 'orange', 'red'])
plt.ylim([0,1])
plt.ylabel('Score')
plt.title('Performance Metrics (Train Data)')
plt.show()

# Testing Data Metrics
test_acc = 0.8637
test_prec = 0.8868
test_rec = 0.8341
test_f1 = 0.8597

print(f"Accuracy:  {train_acc:.4f}")
print(f"Precision: {train_prec:.4f}")
print(f"Recall:    {train_rec:.4f}")
print(f"F1-Score:  {train_f1:.4f}\n")

# Plot Testing Performance Metrics
test_values = [test_acc, test_prec, test_rec, test_f1]

plt.figure(figsize=(8,5))
plt.bar(metrics, test_values, color=['blue', 'green', 'orange', 'red'])
plt.ylim([0,1])
plt.ylabel('Score')
plt.title('Performance Metrics (Test Data)')
plt.show()

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Dropout, Embedding, Conv1D, GlobalMaxPooling1D, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from transformers import TFAutoModel
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from google.colab import drive
import pickle

# Mount Google Drive (if running on Colab)
drive.mount('/content/drive')

# -----------------------------
# Step 1: Load Train Data
# -----------------------------
train_path = "/content/drive/My Drive/fakenews/train.csv"
if not os.path.exists(train_path):
    raise FileNotFoundError("train.csv not found!")
train_df = pd.read_csv(train_path)

# -----------------------------
# Step 2: Preprocess Data
# -----------------------------
train_df['title'] = train_df['title'].fillna("")
train_df['text'] = train_df['text'].fillna("")
train_df['author'] = train_df['author'].fillna("")  # Include author column

# Combine all textual features
train_df['combined_text'] = train_df['author'] + " " + train_df['title'] + " " + train_df['text']

# Tokenization parameters
max_len = 128
vocab_size = 10000
embedding_dim = 128

# Initialize and fit the Keras Tokenizer
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(train_df['combined_text'])
X_train_seq = tokenizer.texts_to_sequences(train_df['combined_text'])
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, dtype='int32')

# -----------------------------
# Step 3: Load Pretrained DeBERTa Model
# -----------------------------
print("Loading DeBERTa model...")
transformer = TFAutoModel.from_pretrained("microsoft/deberta-v3-small")

def extract_embeddings(model, input_ids, batch_size=16):
    all_embeddings = []
    for i in range(0, input_ids.shape[0], batch_size):
        batch_input_ids = tf.convert_to_tensor(input_ids[i:i+batch_size])
        # Use the [CLS] token embedding (index 0)
        batch_embeddings = model(batch_input_ids).last_hidden_state[:, 0, :]
        all_embeddings.append(batch_embeddings.numpy())
    return np.concatenate(all_embeddings, axis=0)

# Extract transformer embeddings (shape: (num_samples, 768))
X_train_bert = extract_embeddings(transformer, X_train_pad, batch_size=16)
print("Shape of DeBERTa embeddings:", X_train_bert.shape)

# -----------------------------
# Step 4: Define CNN Model for Feature Extraction
# -----------------------------
# CNN architecture definition
def create_embedding_cnn():
    input_tensor = Input(shape=(max_len,))
    x = Embedding(vocab_size, embedding_dim, input_length=max_len)(input_tensor)
    x = Conv1D(128, 5, activation='relu')(x)
    x = GlobalMaxPooling1D()(x)
    return Model(input_tensor, x)

cnn_model = create_embedding_cnn()

# Make sure you run predict once to initialize the layers
X_train_cnn = cnn_model.predict(X_train_pad)

# Explicitly build CNN model before saving weights
cnn_model.build(input_shape=(None, max_len))

# Now correctly save CNN weights
cnn_model.save_weights("/content/drive/My Drive/fakenews/embedding_cnn_model.weights.h5")
print("✅ CNN Embedding model weights saved correctly!")


embedding_cnn_model = create_embedding_cnn()
X_train_cnn = embedding_cnn_model.predict(X_train_pad)
print("Shape of CNN features:", X_train_cnn.shape)

# -----------------------------
# Step 5: Combine Features
# -----------------------------
# Combined features: transformer embeddings (768-dim) + CNN features (128-dim) = 896-dim vector.
X_train_features = np.concatenate([X_train_bert, X_train_cnn], axis=1)
print("Shape of combined features:", X_train_features.shape)

# -----------------------------
# Step 6: Define Discriminator Model
# -----------------------------
class Discriminator(Model):
    def __init__(self):
        super(Discriminator, self).__init__()
        self.dense1 = Dense(512, activation='relu')
        self.batch_norm1 = BatchNormalization()
        self.dense2 = Dense(256, activation='relu')
        self.batch_norm2 = BatchNormalization()
        self.dropout1 = Dropout(0.3)
        self.dense3 = Dense(128, activation='relu')
        self.batch_norm3 = BatchNormalization()
        self.dense4 = Dense(1, activation='sigmoid')

    def call(self, inputs):
        x = self.dense1(inputs)
        x = self.batch_norm1(x)
        x = self.dense2(x)
        x = self.batch_norm2(x)
        x = self.dropout1(x)
        x = self.dense3(x)
        x = self.batch_norm3(x)
        return self.dense4(x)

# -----------------------------
# Optimized Learning Rate Strategy
# -----------------------------
initial_learning_rate = 5e-4
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate,
    decay_steps=1000,
    decay_rate=0.96,
    staircase=True
)
optimizer = Adam(learning_rate=lr_schedule)

discriminator = Discriminator()
discriminator.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# -----------------------------
# Step 7: Train Model
# -----------------------------
y_train = train_df['label'].values
discriminator.fit(X_train_features, y_train, validation_split=0.2, epochs=200, batch_size=128)

# -----------------------------
# Step 8: Evaluate Model
# -----------------------------
y_train_pred_prob = discriminator.predict(X_train_features)
y_train_pred = (y_train_pred_prob > 0.45).astype(int)

accuracy = accuracy_score(y_train, y_train_pred)
precision = precision_score(y_train, y_train_pred)
recall = recall_score(y_train, y_train_pred)
f1 = f1_score(y_train, y_train_pred)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("\nClassification Report:\n", classification_report(y_train, y_train_pred))

cm = confusion_matrix(y_train, y_train_pred)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Real', 'Fake'], yticklabels=['Real', 'Fake'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Train Data)')
plt.show()

# -----------------------------
# Step 9: Save Models and Tokenizer
# -----------------------------
# Save the trained discriminator model to Google Drive.
discriminator.save("/content/drive/My Drive/fakenews/fake_news_discriminator_optimized.h5")
print("✅ Discriminator model saved!")


with open("/content/drive/My Drive/fakenews/tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)
print("✅ Tokenizer saved!")

embedding_cnn_model.save("/content/drive/My Drive/fakenews/embedding_cnn_model1.h5")
print("✅ Embedding CNN model saved!")

embedding_cnn_model.save_weights("/content/drive/My Drive/fakenews/embedding_cnn_model.weights.h5")



# Create a pure Python tokenizer state
tokenizer_json = tokenizer.to_json()

# Save tokenizer as JSON (best way to avoid version conflicts)
with open("/content/drive/My Drive/fakenews/tokenizer.json", "w") as f:
    f.write(tokenizer_json)

print("✅ Tokenizer JSON saved!")